# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:Aa123456@tcp(47.105.177.166:9090)/go_gateway_test2?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100